---

- name: Provision a DEBUG {{ application_name }} web server
  hosts: 192.168.108.137
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml

  roles:
    - base
    - rabbitmq
    - web
    - celery
